apiVersion: v1
kind: ReplicationController
metadata:
    name: gameoflife
spec:
  minReadySeconds: 2
  replicas: 5
  selector:
    app: gameoflife
    version: "1.0"
  template:
    metadata:
      name: gameoflife
      labels:
        app: gameoflife
        version: "1.0"
    spec:
      initContainers:
        - name: alpine 
          image: alpine:1.0
          command:
            - sleep
          args :
            - "2m"
      containers:
        - name: openmrs
          image: maheshryali/gameoflife:1.0
          ports:
             - containerPort: 8080
               protocol: TCP

          



